package dev.kaua.squash.Tools;

public abstract class ErrorHelper {
    public static final String LOAD_SOME_FILE_ERROR = "L-143";
    public static final String PROFILE_EDIT = "01";
    public static final String PROFILE_EDIT_IMAGE_UPLOAD = "02";
    public static final String PROFILE_EDIT_IMAGE_CROP = "03";
    public static final String EMAIL_SYSTEM_RE_SEND = "04";
    public static final String NEW_POST_COMPOSE = "05";
    public static final String NEW_POST_COMPOSE_IMAGE_UPLOAD = "06";
    public static final String DELETE_POST_REPORT_API = "07";
    public static final String FORGOT_PASSWORD_NEXT_API = "08";
    public static final String FORGOT_PASSWORD_CODE_VALIDATION_API = "09";
    public static final String FORGOT_PASSWORD_DO_PASSWORD_RESET = "10";
    public static final String PROFILE_FOLLOW_AN_USER = "11";
    public static final String PROFILE_UNFOLLOW_AN_USER = "12";
    public static final String PROFILE_GET_ANOTHER_USER_INFO = "13";
    public static final String PROFILE_MENTION_CLICK = "14";
    public static final String POST_MENTION_CLICK = "15";
    public static final String POST_DELETE_ACTION = "16";
    public static final String POST_DETAIL_DELETE_ACTION = "17";
    public static final String POST_DETAIL_COMMENT_ACTION = "18";
    public static final String POST_DETAIL_LIKE_ACTION = "19";
    public static final String NOTIFICATION_SENDER_POST_COMMENT = "20";
    public static final String POST_DETAIL_LOAD_INFO = "21";
    public static final String QRCODE_GET_USER = "22x";
    public static final String USER_CHAT_ITEM_CLICK = "23";
    public static final String SIGN_UP_ACTION = "24";
    public static final String EMAIL_VALIDATION_TRY_VALIDATE = "25";
    public static final String BACKGROUND_HELPER_UPLOAD = "26";
    public static final String COMMENT_LIKE_ACTION = "27";
    public static final String FOLLOWING_FOLLOWERS_CLICK = "28";
    public static final String PROFILE_IMAGE_UPLOAD = "29";
    public static final String FOLLOWING_SHOW_LIST = "30";
    public static final String LOGIN_ACTION = "31";
    public static final String LOGIN_ACTION_PASSWORD_EMAIL_WARNING = "32";
    public static final String LOGIN_ACTION_RE_CREATE_FIREBASE = "32/S";
    public static final String LOAD_FEED_POSTS = "33";
    public static final String WARN_USER_WITHOUT_ID = "34";
    public static final String WARN_USER_SERVER_ERROR = "35";
    public static final String REPORT_AN_USER = "36";
    public static final String UPDATE_BASE_INFO_REQUEST = "37";
    public static final String UPDATE_BASE_INFO_FAILURE = "37/2";
    public static final String REQUEST_VERIFICATION_REQUEST = "38";
    public static final String REQUEST_VERIFICATION_FAILURE = "38/2";
    public static final String GOOGLE_TEST_FAILURE = "39";
}